const products = [
  {
    id: 1,
    name: "Classic Cheeseburger",
    rating: 4.5,
    price: 7,
    category: "Burger",
    img: "/images/products/burger1.jpg",
  },
  {
    id: 2,
    name: "Chicken Burger",
    rating: 4.5,
    price: 7,
    category: "Burger",
    img: "/images/products/burger2.jpg",
  },
  {
    id: 3,
    name: "Doppeldecker",
    rating: 4.5,
    price: 7,
    category: "Burger",
    img: "/images/products/burger3.jpg",
  },
  {
    id: 4,
    name: "Monster Double Patty",
    rating: 4.5,
    price: 25,
    category: "Burger",
    img: "/images/products/burger4.jpg",
  },
  {
    id: 5,
    name: "Berry Crumble Pie",
    rating: 4.5,
    price: 7,
    category: "Dessert",
    img: "/images/products/deserts1.jpg",
  },
  {
    id: 6,
    name: "Croissant mit Toppings",
    rating: 4.5,
    price: 7,
    category: "Dessert",
    img: "/images/products/deserts2.jpg",
  },
  {
    id: 7,
    name: "Apfel-Zimt Kuchen",
    rating: 4.5,
    price: 7,
    category: "Dessert",
    img: "/images/products/deserts3.jpg",
  },
  {
    id: 8,
    name: "Biskuitrolle",
    rating: 4.5,
    price: 7,
    category: "Dessert",
    img: "/images/products/deserts4.jpg",
  },
  {
    id: 9,
    name: "Frosted Ember",
    rating: 4.5,
    price: 7,
    category: "Dessert",
    img: "/images/products/deserts8.jpg",
  },
  {
    id: 10,
    name: "Nudeln mit Chicken",
    rating: 4.5,
    price: 19,
    category: "Nudeln",
    img: "/images/products/noodles1.jpg",
  },
  {
    id: 11,
    name: "Karpfen Klassiker",
    rating: 4.3,
    price: 18,
    category: "Nudeln",
    img: "/images/products/noodles2.jpg",
  },
  {
    id: 12,
    name: "Meereszauber Spaghetti",
    rating: 3.9,
    price: 25,
    category: "Nudeln",
    img: "/images/products/noodles3.jpg",
  },
  {
    id: 13,
    name: "Ramen Genuss",
    rating: 4.4,
    price: 22,
    category: "Nudeln",
    img: "/images/products/noodles4.jpg",
  },
  {
    id: 14,
    name: "Waldpilz-Pasta",
    rating: 4.5,
    price: 16,
    category: "Nudeln",
    img: "/images/products/noodles5.jpg",
  },
  {
    id: 15,
    name: "Ei-Salat",
    rating: 4.6,
    price: 16,
    category: "Salat",
    img: "/images/products/salat1.jpg",
  },
  {
    id: 16,
    name: "Garnelensalat",
    rating: 4.8,
    price: 19,
    category: "Salat",
    img: "/images/products/salat2.jpg",
  },
  {
    id: 17,
    name: "Quinoasalat mit Gemüse",
    rating: 4.8,
    price: 14,
    category: "Salat",
    img: "/images/products/salat3.jpg",
  },
  {
    id: 18,
    name: "Liba. Petersiliensalat",
    rating: 4.2,
    price: 14,
    category: "Salat",
    img: "/images/products/salat4.jpg",
  },
  {
    id: 19,
    name: "Classic Cheeseburger",
    rating: 4,
    price: 13,
    category: "Salat",
    img: "/images/products/salat5.jpg",
  },
  {
    id: 20,
    name: "Classic Cheeseburger",
    rating: 4.7,
    price: 17,
    category: "Salat",
    img: "/images/products/salat6.jpg",
  },
  {
    id: 21,
    name: "Classic Cheeseburger",
    rating: 4.1,
    price: 8,
    category: "Snacks",
    img: "/images/products/snacks1.jpg",
  },
  {
    id: 22,
    name: "Classic Cheeseburger",
    rating: 4.1,
    price: 8,
    category: "Snacks",
    img: "/images/products/snacks2.jpg",
  },
  {
    id: 23,
    name: "Classic Cheeseburger",
    rating: 4.1,
    price: 8,
    category: "Snacks",
    img: "/images/products/snacks3.jpg",
  },
  {
    id: 24,
    name: "Classic Cheeseburger",
    rating: 4.1,
    price: 8,
    category: "Snacks",
    img: "/images/products/snacks4.jpg",
  },
  {
    id: 25,
    name: "Tomate-Morzarella",
    rating: 4.6,
    price: 9,
    category: "Salat",
    img: "/images/products/salat9.jpg",
  },
  {
    id: 26,
    name: "Tomate-Morzarella",
    rating: 4.6,
    price: 9,
    category: "Rolls",
    img: "/images/products/rolls1.jpg",
  },
  {
    id: 27,
    name: "Tomate-Morzarella",
    rating: 4.6,
    price: 9,
    category: "Rolls",
    img: "/images/products/rolls2.jpg",
  },
  {
    id: 28,
    name: "Tomate-Morzarella",
    rating: 4.6,
    price: 9,
    category: "Rolls",
    img: "/images/products/rolls3.jpg",
  },
];

export default products;
