const products = [
  {
    id: 1,
    name: "Classic Cheeseburger",
    price: 12,
    category: "Burger",
    img: "/images/products/burger1.jpg",
    description:
      "Weizenbrötchen, Rindfleisch, Käse, Salat, Tomate, Zwiebel, Gurke, Sauce",
  },
  {
    id: 2,
    name: "Chicken Burger",
    price: 12,
    category: "Burger",
    img: "/images/products/burger2.jpg",
    description:
      "Weizenbrötchen, Rindfleisch, Käse, Salat, Tomate, Zwiebel, Gurke, Sauce",
  },
  {
    id: 3,
    name: "Doppeldecker",
    price: 15,
    category: "Burger",
    img: "/images/products/burger3.jpg",
    description:
      "Weizenbrötchen, Rindfleisch, Käse, Salat, Tomate, Zwiebel, Gurke, Sauce",
  },
  {
    id: 4,
    name: "Monster Double Patty",
    price: 25,
    category: "Burger",
    img: "/images/products/burger4.jpg",
    description:
      "Weizenbrötchen, Rindfleisch, Käse, Salat, Tomate, Zwiebel, Gurke, Sauce",
  },
  {
    id: 5,
    name: "Berry Crumble Pie",
    price: 11,
    category: "Dessert",
    img: "/images/products/deserts1.jpg",
    description: "Schokolade, Sahne, Früchte, Keks, Vanilleeis",
  },
  {
    id: 6,
    name: "Croissant mit Toppings",
    price: 7,
    category: "Dessert",
    img: "/images/products/deserts2.jpg",
    description: "Schokolade, Sahne, Früchte, Keks, Vanilleeis",
  },
  {
    id: 7,
    name: "Apfel-Zimt Kuchen",
    price: 12,
    category: "Dessert",
    img: "/images/products/deserts3.jpg",
    description: "Schokolade, Sahne, Früchte, Keks, Vanilleeis",
  },
  {
    id: 8,
    name: "Biskuitrolle",
    price: 9,
    category: "Dessert",
    img: "/images/products/deserts4.jpg",
    description: "Schokolade, Sahne, Früchte, Keks, Vanilleeis",
  },
  {
    id: 9,
    name: "Frosted Ember",
    price: 5,
    category: "Dessert",
    img: "/images/products/deserts8.jpg",
    description: "Schokolade, Sahne, Früchte, Keks, Vanilleeis",
  },
  {
    id: 10,
    name: "Nudeln mit Chicken",
    price: 19,
    category: "Nudeln",
    img: "/images/products/noodles1.jpg",
    description: "Spaghetti, Tomatensauce, Parmesan, Basilikum, Olivenöl",
  },
  {
    id: 11,
    name: "Karpfen Klassiker",
    price: 18,
    category: "Nudeln",
    img: "/images/products/noodles2.jpg",
    description: "Spaghetti, Tomatensauce, Parmesan, Basilikum, Olivenöl",
  },
  {
    id: 12,
    name: "Meereszauber Spaghetti",
    price: 25,
    category: "Nudeln",
    img: "/images/products/noodles3.jpg",
    description: "Spaghetti, Tomatensauce, Parmesan, Basilikum, Olivenöl",
  },
  {
    id: 13,
    name: "Ramen Genuss",
    price: 22,
    category: "Nudeln",
    img: "/images/products/noodles4.jpg",
    description: "Spaghetti, Tomatensauce, Parmesan, Basilikum, Olivenöl",
  },
  {
    id: 14,
    name: "Waldpilz-Pasta",
    price: 16,
    category: "Nudeln",
    img: "/images/products/noodles5.jpg",
    description: "Spaghetti, Tomatensauce, Parmesan, Basilikum, Olivenöl",
  },
  {
    id: 15,
    name: "Ei-Salat",
    price: 16,
    category: "Salat",
    img: "/images/products/salat1.jpg",
    description:
      "Blattsalat, Tomate, Gurke, Paprika, Karotte, Oliven, Dressing",
  },
  {
    id: 16,
    name: "Garnelensalat",
    price: 19,
    category: "Salat",
    img: "/images/products/salat2.jpg",
    description:
      "Blattsalat, Tomate, Gurke, Paprika, Karotte, Oliven, Dressing",
  },
  {
    id: 17,
    name: "Quinoasalat mit Gemüse",
    price: 14,
    category: "Salat",
    img: "/images/products/salat3.jpg",
    description:
      "Blattsalat, Tomate, Gurke, Paprika, Karotte, Oliven, Dressing",
  },
  {
    id: 18,
    name: "Liba. Petersiliensalat",
    price: 14,
    category: "Salat",
    img: "/images/products/salat4.jpg",
    description:
      "Blattsalat, Tomate, Gurke, Paprika, Karotte, Oliven, Dressing",
  },
  {
    id: 19,
    name: "Oliven Salat",
    price: 13,
    category: "Salat",
    img: "/images/products/salat5.jpg",
    description:
      "Blattsalat, Tomate, Gurke, Paprika, Karotte, Oliven, Dressing",
  },
  {
    id: 20,
    name: "Hummus Salat",
    price: 17,
    category: "Salat",
    img: "/images/products/salat6.jpg",
    description:
      "Blattsalat, Tomate, Gurke, Paprika, Karotte, Oliven, Dressing",
  },
  {
    id: 21,
    name: "Frühstück's Toast",
    price: 9,
    category: "Snacks",
    img: "/images/products/snacks1.jpg",
    description: "Pommes, Ketchup, Mayonnaise, Salz, Paprikapulver",
  },
  {
    id: 22,
    name: "Pommes",
    price: 10,
    category: "Snacks",
    img: "/images/products/snacks2.jpg",
    description: "Pommes, Ketchup, Mayonnaise, Salz, Paprikapulver",
  },
  {
    id: 23,
    name: "Crispy Chicken",
    price: 18,
    category: "Snacks",
    img: "/images/products/snacks3.jpg",
    description: "Pommes, Ketchup, Mayonnaise, Salz, Paprikapulver",
  },
  {
    id: 24,
    name: "Zwiebelringe",
    price: 15,
    category: "Snacks",
    img: "/images/products/snacks4.jpg",
    description: "Pommes, Ketchup, Mayonnaise, Salz, Paprikapulver",
  },
  {
    id: 25,
    name: "Tomate-Morzarella",
    price: 11,
    category: "Salat",
    img: "/images/products/salat9.jpg",
    description: "Pommes, Ketchup, Mayonnaise, Salz, Paprikapulver",
  },
  {
    id: 26,
    name: "Wrap Vegan",
    price: 12,
    category: "Rolls",
    img: "/images/products/rolls1.jpg",
    description: "Weizenteig, Hähnchen, Salat, Gurke, Karotte, Sauce",
  },
  {
    id: 27,
    name: "Wrap mit Hackfleisch",
    price: 13,
    category: "Rolls",
    img: "/images/products/rolls2.jpg",
    description: "Weizenteig, Hähnchen, Salat, Gurke, Karotte, Sauce",
  },
  {
    id: 28,
    name: "Wrap mit Gemüse",
    price: 11,
    category: "Rolls",
    img: "/images/products/rolls3.jpg",
    description: "Weizenteig, Hähnchen, Salat, Gurke, Karotte, Sauce",
  },
];

export default products;
